from tkinter import *
from tkinter import ttk
from PIL import Image,ImageTk
from tkinter.messagebox import *
import mysql.connector
from login import ee

def clear():
    n.delete(0, END)
    n2.delete(0, END)
    n3.delete(0, END)
    n4.delete(0, END)
    n5.delete(0, END)
    n6.delete(0, END)
    n7.delete(0, END)

window=Tk()
img=PhotoImage(file='icon.png')
window.tk.call('wm','iconphoto',window._w,img)
window.title('DocHouse')  
window.geometry('1200x800')
bglogin = PhotoImage(file='bgg.png')
bgloginLabel = Label(window, image=bglogin)
bgloginLabel.place(x=0, y=0)
Frame1 = Frame(window, bg='white', width=800, height=450)
Frame1.place(x=220, y=80)
con = mysql.connector.connect(host='localhost', user='root', password='root', database='doctors')
cur = con.cursor(dictionary=True)
cur.execute("select * from userschoice where email='"+ee+"'")
row = cur.fetchall()
for i in row:
    li=list(i.values())
    lab=Label(Frame1,text="reservation details: ", font=('times new roman', 18, 'bold'), bg='white',fg='#009973')
    lab.place(x=320,y=0)
    l = Label(Frame1, text="The address is: ", font=('times new roman', 18, 'bold'), bg='white',fg='#009973' )
    l.place(x=130,y=50)
    n=Label(Frame1, text=li[0], font=('times new roman', 18, 'bold'), bg='white',fg='gray20' )
    n.place(x=300,y=50)
    l2 = Label(Frame1, text="The Gender is (1 for male, 2 for female): ", font=('times new roman', 18, 'bold'), bg='white',fg='#009973' )
    l2.place(x=130,y=100)
    n2=Label(Frame1, text=li[1], font=('times new roman', 18, 'bold'), bg='white',fg='gray20' )
    n2.place(x=550,y=100)
    l3 = Label(Frame1, text="The day is: ", font=('times new roman', 18, 'bold'), bg='white',fg='#009973' )
    l3.place(x=130,y=150)
    n3=Label(Frame1, text=li[2], font=('times new roman', 18, 'bold'), bg='white',fg='gray20' )
    n3.place(x=250,y=150)
    l4 = Label(Frame1, text="The cost is: ", font=('times new roman', 18, 'bold'), bg='white',fg='#009973' )
    l4.place(x=130,y=200)
    n4=Label(Frame1, text=li[3], font=('times new roman', 18, 'bold'), bg='white',fg='gray20' )
    n4.place(x=250,y=200)
    l5 = Label(Frame1, text="The age is: ", font=('times new roman', 18, 'bold'), bg='white',fg='#009973' )
    l5.place(x=130,y=250)
    n5=Label(Frame1, text=li[4], font=('times new roman', 18, 'bold'), bg='white',fg='gray20' )
    n5.place(x=250,y=250)
    l6 = Label(Frame1, text="The governorate is: ", font=('times new roman', 18, 'bold'), bg='white',fg='#009973' )
    l6.place(x=130,y=300)
    n6=Label(Frame1, text=li[5], font=('times new roman', 18, 'bold'), bg='white',fg='gray20' )
    n6.place(x=350,y=300)
    l7 = Label(Frame1, text="The specialization and the doctor name are: ", font=('times new roman', 18, 'bold'), bg='white',fg='#009973' )
    l7.place(x=130,y=350)
    n7=Label(Frame1, text=li[6], font=('times new roman', 18, 'bold'), bg='white',fg='gray20' )
    n7.place(x=130,y=400)
window.mainloop()
clear()
window.destroy()